# Generated by Django 5.2.14 on 2026-05-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetricsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("spend", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("cpm", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("ctr", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("frequency", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("reach", models.BigIntegerField(default=0)),
                ("outbound_clicks", models.BigIntegerField(default=0)),
                (
                    "outbound_clicks_ctr",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("landing_page_views", models.BigIntegerField(default=0)),
                ("add_to_cart", models.BigIntegerField(default=0)),
                ("purchases", models.BigIntegerField(default=0)),
                ("purchase_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("leads", models.BigIntegerField(default=0)),
                ("source", models.CharField(default="manual", max_length=8)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="clients.metaadaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "account_id"],
                "indexes": [
                    models.Index(fields=["account", "-date"], name="dashboard_d_account_36883e_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("account", "date"), name="uniq_account_date")
                ],
            },
        ),
    ]
