# Generated by Django 5.2.14 on 2026-05-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_facebook_socialapp"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clients.metaadaccount",
            ),
        ),
    ]
