# Generated by Django 5.2.14 on 2026-05-13 05:03

import django.db.models.deletion
from django.db import migrations, models

import apps.clients.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_roas",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "target_cpl",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "target_cpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "min_test_spend",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientMetaCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("access_token", apps.clients.fields.encrypt(models.TextField(blank=True))),
                ("fallback_token", apps.clients.fields.encrypt(models.TextField(blank=True))),
                ("api_version", models.CharField(default="v22.0", max_length=8)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaAdAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_id", models.CharField(max_length=40, unique=True)),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("timezone_offset", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["account_name", "account_id"],
                "indexes": [
                    models.Index(
                        fields=["client", "is_active"], name="clients_met_client__de4abd_idx"
                    )
                ],
            },
        ),
    ]
